name: "Laravel CI"

on:
  push:
    branches:
      - 'main'

  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - 'main'

permissions:
  contents: read

jobs:
  laravel-tests:
    uses: ./.github/workflows/reusable-ci.yaml
    secrets:
      APP_KEY_CI: ${{ secrets.APP_KEY_CI }}
