name: Deploy to Production

on:
  push:
    tags:
      - 'v*.*.*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  laravel-tests:
    uses: ./.github/workflows/reusable-ci.yaml
    secrets:
      APP_KEY_CI: ${{ secrets.APP_KEY_CI }}

  build-image:
    uses: ./.github/workflows/reusable-build-production.yaml
    needs: [ laravel-tests ]
    with:
      project_name: ${{ vars.PROJECT_NAME }}
      commit_sha: ${{ github.sha }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  deploy-production:
    needs: [ build-image, laravel-tests ]
    uses: ./.github/workflows/reusable-deploy-production.yaml
    with:
      commit_sha: ${{ github.sha }}
      project_name: ${{ vars.PROJECT_NAME }}
      tag: ${{ github.ref_name }}
      domain_production: ${{ vars.DOMAIN_PRODUCTION }}
    secrets:
      VPS_HOST: ${{ secrets.VPS_HOST }}
      VPS_USER: ${{ secrets.VPS_USER }}
      VPS_SSH_KEY: ${{ secrets.VPS_SSH_KEY }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
