name: Deploy to Production

on:
  push:
    tags:
      - 'v*.*.*'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  laravel-tests:
    if: |
      github.event.base_ref == 'refs/heads/main'
      || github.event.base_ref == 'refs/heads/feature/create-production-workflow-flow-only-for-tag-push'
    uses: ./.github/workflows/reusable-ci.yaml
    secrets:
      APP_KEY_CI: ${{ secrets.APP_KEY_CI }}

  build-image:
    runs-on: ubuntu-latest
    needs: [ laravel-tests ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ github.repository }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          target: php
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            COMPOSER_CACHE_VERSION=${{ hashFiles('composer.lock') }}
            NPM_CACHE_VERSION=${{ hashFiles('package-lock.json') }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy_production:
    runs-on: ubuntu-latest
    needs: [ laravel-tests, build-image ]
    environment:
      name: Production
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            echo "Deploying to production..."
