name: Ephemeral Preview Environment

on:
  pull_request:
    types: [ opened, synchronize, reopened, closed, labeled, unlabeled ]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  laravel-tests-preview:
    uses: ./.github/workflows/reusable-ci.yaml
    if: |
      (
        contains(vars.ALLOWED_AUTHOR_ASSOCIATIONS, github.event.pull_request.author_association)
      )
      && (
        contains(github.event.pull_request.labels.*.name, vars.DEPLOY_PREVIEW_LABEL)
      )
      && (
        github.event.pull_request.head.repo.full_name == github.repository
      )
      && (
        github.event.action != 'closed'
      )
    secrets:
      APP_KEY_CI: ${{ secrets.APP_KEY_CI }}

  build_image:
    runs-on: ubuntu-latest
    needs: [ laravel-tests-preview ]
    steps:
      - name: Run build image
        run: |
          echo "✅ build image successfully created!"

  deploy_preview:
    runs-on: ubuntu-latest
    needs: [ laravel-tests-preview, build_image ]
    environment:
      name: Preview
    steps:
      - name: Run deploy environment preview
        run: |
          echo "✅ deploy environment preview successfully created!"

  destroy_preview:
    runs-on: ubuntu-latest
    if: |
      (
        contains(vars.ALLOWED_AUTHOR_ASSOCIATIONS, github.event.pull_request.author_association)
      )
      && (
        github.event.pull_request.head.repo.full_name == github.repository
      )
      && (
        github.event.action == 'closed'
      )
    environment:
      name: Preview
    steps:
      - name: Run destroy environment preview
        run: |
          echo "✅ destroy environment preview successfully created!"
