name: Ephemeral Preview Environment

on:
  pull_request:
    types: [ opened, synchronize, reopened, closed, labeled, unlabeled ]

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  laravel-tests:
    uses: ./.github/workflows/reusable-ci.yaml
    if: |
      (
        contains(vars.ALLOWED_AUTHOR_ASSOCIATIONS, github.event.pull_request.author_association)
      )
      && (
        contains(github.event.pull_request.labels.*.name, vars.DEPLOY_PREVIEW_LABEL)
      )
      && (
        github.event.pull_request.head.repo.full_name == github.repository
      )
      && (
        github.event.action != 'closed'
      )
    secrets:
      APP_KEY_CI: ${{ secrets.APP_KEY_CI }}

  build-image:
    uses: ./.github/workflows/reusable-build-preview.yaml
    needs: [ laravel-tests ]
    if: |
      (
        contains(vars.ALLOWED_AUTHOR_ASSOCIATIONS, github.event.pull_request.author_association)
      )
      && (
        contains(github.event.pull_request.labels.*.name, vars.DEPLOY_PREVIEW_LABEL)
      )
      && (
        github.event.pull_request.head.repo.full_name == github.repository
      )
      && (
        github.event.action != 'closed'
      )
    with:
      pr_number: ${{ github.event.pull_request.number }}
      project_name: ${{ vars.PROJECT_NAME }}
      label_preview: ${{ vars.LABEL_PREVIEW }}
      commit_sha: ${{ github.event.pull_request.head.sha }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  deploy-preview:
    needs: [ build-image, laravel-tests ]
    if: |
      (
        contains(vars.ALLOWED_AUTHOR_ASSOCIATIONS, github.event.pull_request.author_association)
      )
      && (
        contains(github.event.pull_request.labels.*.name, vars.DEPLOY_PREVIEW_LABEL)
      )
      && (
        github.event.pull_request.head.repo.full_name == github.repository
      )
      && (
        github.event.action != 'closed'
      )
    uses: ./.github/workflows/reusable-deploy-preview.yaml
    with:
      pr_number: ${{ github.event.pull_request.number }}
      commit_sha: ${{ github.event.pull_request.head.sha }}
      project_name: ${{ vars.PROJECT_NAME }}
      repo_full_name: ${{ github.repository }}
      domain_preview: ${{ vars.DOMAIN_PREVIEW }}
      label_preview: ${{ vars.LABEL_PREVIEW }}
    secrets:
      VPS_HOST: ${{ secrets.VPS_HOST }}
      VPS_USER: ${{ secrets.VPS_USER }}
      VPS_SSH_KEY: ${{ secrets.VPS_SSH_KEY }}

  destroy-preview:
    if: |
      (
        contains(vars.ALLOWED_AUTHOR_ASSOCIATIONS, github.event.pull_request.author_association)
      )
      && (
        github.event.pull_request.head.repo.full_name == github.repository
      )
      && (
        github.event.action == 'closed'
        || (github.event.action == 'unlabeled' && github.event.label.name == vars.DEPLOY_PREVIEW_LABEL)
      )
    uses: ./.github/workflows/reusable-destroy-preview.yaml
    with:
      pr_number: ${{ github.event.pull_request.number }}
      project_name: ${{ vars.PROJECT_NAME }}
      repo_full_name: ${{ github.repository }}
      domain_preview: ${{ vars.DOMAIN_PREVIEW }}
      label_preview: ${{ vars.LABEL_PREVIEW }}
    secrets:
      VPS_HOST: ${{ secrets.VPS_HOST }}
      VPS_USER: ${{ secrets.VPS_USER }}
      VPS_SSH_KEY: ${{ secrets.VPS_SSH_KEY }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
