name: Ephemeral Preview Environment

on:
  pull_request:
    types: [ opened, synchronize, reopened, closed, labeled, unlabeled ]

env:
  PR_NUMBER: ${{ github.event.pull_request.number }}

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  laravel-tests:
    uses: ./.github/workflows/reusable-ci.yaml
    if: |
      (
        contains(vars.ALLOWED_AUTHOR_ASSOCIATIONS, github.event.pull_request.author_association)
      )
      && (
        contains(github.event.pull_request.labels.*.name, vars.DEPLOY_PREVIEW_LABEL)
      )
      && (
        github.event.pull_request.head.repo.full_name == github.repository
      )
      && (
        github.event.action != 'closed'
      )
    secrets:
      APP_KEY_CI: ${{ secrets.APP_KEY_CI }}

  build_image:
    runs-on: ubuntu-latest
    needs: [ laravel-tests ]
    outputs:
      image_tag: ${{ steps.meta.outputs.tags }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ github.repository }}
          tags: |
            type=raw,value=pr-${{ env.PR_NUMBER }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          target: php
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: |
            br.com.carlosalexandre.preview.pr.${{ vars.PROJECT_NAME }}=${{ env.PR_NUMBER }}
            br.com.carlosalexandre.preview.general-${{ vars.PROJECT_NAME }}=true
          build-args: |
            COMPOSER_CACHE_KEY=${{ hashFiles('composer.lock') }}
            NPM_CACHE_KEY=${{ hashFiles('package-lock.json') }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy_preview:
    runs-on: ubuntu-latest
    needs: [ laravel-tests, build_image ]
    environment:
      name: Preview
    steps:
      - name: Run deploy environment preview
        run: |
          echo "✅ deploy environment preview successfully created!"

  destroy_preview:
    runs-on: ubuntu-latest
    if: |
      (
        contains(vars.ALLOWED_AUTHOR_ASSOCIATIONS, github.event.pull_request.author_association)
      )
      && (
        github.event.pull_request.head.repo.full_name == github.repository
      )
      && (
        github.event.action == 'closed'
        || (github.event.action == 'unlabeled' && github.event.label.name == vars.DEPLOY_PREVIEW_LABEL)
      )
    environment:
      name: Preview
    steps:
      - name: Run destroy environment preview
        run: |
          echo "✅ destroy environment preview successfully created!"
